version: "3.8"

services:
  tic-tac-toe:
    build:
      context: .
      dockerfile: Dockerfile  # Update the path if your Dockerfile is located elsewhere
    ports:
      - "80:80"
    restart: always
